### ISSUE TITLE
Make the Random Function in the Backend 🚂

### ISSUE THREAD

**Issue by iamBijoyKar** [TechStarHub/quotes#2]
## Info 🎟

- The backend is made with `Express`.
- There is already provided `json` file in `backend/data` directory, that contains multiple quotes. 
- The entry point of backend is `backend/index.js` 

## Job ⛑

Make a function that must return a random quote from the provided `json `file, this function should respond to `/rand` route.

**Comment by Amir-Helali** [comment]
@iamBijoyKar I would like to work on this issue if you are okay with that.

**Comment by Amir-Helali** [comment]
@iamBijoyKar I submitted a PR that resolves this issue. Please let me know if that works for you or if you need me to make any changes to it. Thank you!

**Comment by iamBijoyKar** [comment]
Nice work 👍
